config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { registrations: "registrations" }
  root 'posts#index'
  get "/users/:id", to: "users#show", as:"user"
  
  resources :posts, only: %i(new create index show destroy) do
    resources :photos, only: %i(create)
      resources :likes, only: %i(create destroy)
        resources :comments, only: %i(create destroy)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :post
  
  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :post

  validates :image, presence: true

  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :comments, dependent: :destroy

  accepts_nested_attributes_for :photos

  def liked_by(user)
    Like.find_by(user_id: user.id, post_id: id)
  end
end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy
  has_many :likes
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 50 }

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!

  def create
    @comment = Comment.new(comment_params)
    @post = @comment.post
    if @comment.save
      respond_to :js
    else
      flash[:alert] = "コメントに失敗しました"
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @post = @comment.post
    if @comment.destroy
      respond_to :js
    else
      flash[:alert] = "コメントの削除に失敗しました"
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:user_id, :post_id, :comment)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :authenticate_user!

  def create
    @like = current_user.likes.build(like_params)
    @post = @like.post
    if @like.save
      respond_to :js
    end
  end

  def destroy
    @like = Like.find_by(id: params[:id])
    @post = @like.post
    if @like.destroy
      respond_to :js
    end
  end

  private
  def like_params
    params.permit(:post_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_post, only: %i(show destroy)

  def new
    @post = Post.new
    @post.photos.build
  end

  def create
    @post = Post.new(post_params)
    if @post.photos.present?
      @post.save
      redirect_to root_path
      flash[:notice] = "投稿が保存されました"
    else
      redirect_to root_path
      flash[:alert] = "投稿に失敗しました"
    end
  end

  def index
    @posts = Post.limit(10).includes(:photos, :user).order("created_at DESC")
  end

    @post
  def show
  end

    @post
  def destroy
    if @post.user == current_user
      flash[:notice] = "投稿が削除されました" if @post.destroy
    else
      flash[:alert] = "投稿の削除が失敗しました"
    end
    redirect_to root_path
  end

private
  def post_params
    params.require(:post).permit(:caption, photos_attributes: [:image]).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find_by(id: params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  def after_update_path_for(resource)
    user_path(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def avatar_url(user)
    return user.profile_photo unless user.profile_photo.nil?
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}.jpg"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.js.haml
$('#comment-post-#{@post.id.to_s}').
html('#{j render "posts/comment_list", { post: @post }}');
$('#comment-form-post-#{@post.id.to_s} #comment_comment').val("");

app/views/comments/destroy.js.haml
$('#comment-post-#{@post.id.to_s}').
html('#{j render "posts/comment_list", { post: @post }}');

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Snsgram
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    #wrapper
      = render "partial/navbar" if current_user
      - if flash[:notice]
        .alert.alert-info
          = flash[:notice]
      - if flash[:alert]
        .alert.alert-danger
          = flash[:alert]
      .container
        = yield
      = render "partial/footer"

app/views/likes/create.js.haml
$('#like-icon-post-#{@post.id.to_s}').
html('#{link_to "いいね", post_like_path(@post.id, @like), method: :DELETE, remote: true, class: "loved hide-text"}');
$('#like-text-post-#{@post.id.to_s}').
html('#{j render "posts/like_text", { likes: @post.likes }}');

app/views/likes/destroy.js.haml
$('#like-icon-post-#{@post.id.to_s}').
html('#{link_to "いいねを取り消す", post_likes_path(@post), method: :POST, remote: true, class: "love hide-text"}');
$('#like-text-post-#{@post.id.to_s}').
html('#{j render "posts/like_text", { likes: @post.likes }}');

app/views/pages/home.html.haml
%p このページは仮のトップページです。
- if user_signed_in?
  = link_to "サインアウト", destroy_user_session_path, method: :delete
= link_to "仮のボタンです", "#", class: "btn btn-primary"

app/views/partial/_footer.html.haml
%footer
  .container
    .text-center
      %p
        Copyright © SNSgram

app/views/partial/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light
  .container
    = link_to "", root_path, class: "navbar__brand navbar__mainLogo"
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.ml-md-auto.align-items-center
        %li
          = link_to "投稿", new_post_path, class: "btn btn-primary"
        %li
          = link_to "", user_path(current_user), class: "nav-link commonNavIcon profile-icon"

app/views/posts/_comment_list.html.haml
- post.comments.each do |comment|
  .mb-2
    - if comment.user == current_user
      = link_to "", post_comment_path(post.id, comment), method: :delete, remote: true, class: "delete-comment"
    %span
      %strong
        = link_to comment.user.name, user_path(comment.user), class: "no-text-decoration black-color"
    %span= comment.comment

app/views/posts/_like_text.html.haml
%strong
  - likes.each.with_index do |like, index|
    - if likes.size == 1
      = "#{like.user.name}が「いいね！」しました"
    - elsif like == likes.last
      and
      %strong
        = "#{like.user.name}が「いいね！」しました"
    - elsif index > 1
      = "#{(likes.size-index).to_s} + 他 が「いいね！」しました"
      - break
    - elsif index == likes.size-2 || index == 1
      = like.user.name
    - else
      = like.user.name

app/views/posts/index.html.haml
- @posts.each do |post|
  .col-md-8.col-md-2.mx-auto
    .card-wrap
      .card
        .card-header.align-items-center.d-flex
          = link_to user_path(post.user), class: "no-text-decoration" do
            = image_tag avatar_url(post.user), class: "post-profile-icon"
          = link_to user_path(post.user), class: "black-color no-text-decoration", |
            title: post.user.name do                                               |
            %strong= post.user.name
          - if post.user_id == current_user.id
            = link_to post_path(post), method: :delete, class: "ml-auto mx-0 my-auto" do
              .delete-post-icon
        = link_to(post_path(post)) do
          = image_tag post.photos.first.image.url(:medium), class: "card-img-top"
        .card-body
          .row.parts
            %div{:id => "like-icon-post-#{post.id.to_s}"}
              - if post.liked_by(current_user).present?
                = link_to "いいねを取り消す", post_like_path(post.id, post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text"
              - else
                = link_to "いいね", post_likes_path(post), method: :POST, remote: true, class: "love hide-text"
            = link_to "", "#", class: "comment"
          %div{:id => "like-text-post-#{post.id.to_s}"}
            = render "like_text", { likes: post.likes }
          %div
            %span
              %strong= post.user.name
            %span= post.caption
            = link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post), class: "post-time no-text-decoration"
            %div{:id => "comment-post-#{post.id.to_s}"}
              = render 'comment_list', { post: post }
            = link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post), |
              class: "light-color post-time no-text-decoration"                         |
            %hr/
            .row.actions{:id => "comment-form-post-#{post.id.to_s}"}
              = form_with model: [post, Comment.new], class: "w-100" do |f|
                = f.hidden_field :user_id, value: current_user.id
                = f.hidden_field :post_id, value: post.id
                = f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off

app/views/posts/new.html.haml
.d-flex.flex-column.align-items-center.mt-3
  .col-xl-7.col-lg-8.col-md-10.col-sm-11.post-card
    .card
      .card-header
        投稿画面
      .card-body
        = form_with model: @post, class: "upload-images p-0 border-0" do |f|
          .form-group.row.mt-2
            .col-auto.pr-0
              = image_tag avatar_url(current_user), class: "post-profile-icon"
            .col.pl-0
              = f.text_field :caption, class: "form-control border-0", placeholder: "キャプションを書く"
          .mb-3
            = f.fields_for :photos do |i|
              = i.file_field :image
          = f.submit "投稿する", class: "btn btn-primary"

app/views/posts/show.html.haml
.col-md-10.col-md-offset-1.mx-auto.postShow-wrap
  .row.post-wrap
    .col-md-8
      .card-left
        = image_tag @post.photos.first.image.url(:medium), class: "card-img-top"
    .col-md-4
      .card-right
        .card-right-comment
          .card-right-name
            = link_to user_path(@post.user), class: "no-text-decoration" do
              = image_tag avatar_url(@post.user), class: "post-profile-icon"
            = link_to user_path(@post.user), class: "black-color no-text-decoration post-user-name", |
              title: @post.user.name do                                                              |
              %strong= @post.user.name
            - if @post.user_id == current_user.id
              = link_to post_path(@post), method: :delete, class: "ml-auto mx-0 my-auto" do
                .delete-post-icon
          .m-2
            %strong
              = @post.caption
          .comment-post-id
            .m-2
              %div{:id => "comment-post-#{@post.id.to_s}"}
                = render 'comment_list', post: @post
        .row.parts
          %div{:id => "like-icon-post-#{@post.id.to_s}"}
            - if @post.liked_by(current_user).present?
              = link_to "いいねを取り消す", post_like_path(@post.id, @post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text"
            - else
              = link_to "いいね", post_likes_path(@post), method: :POST, remote: true, class: "love hide-text"
        %div{:id => "like-text-post-#{@post.id.to_s}"}
          = render "like_text", { likes: @post.likes }
        .post-time
          = time_ago_in_words(@post.created_at).upcase
          前
        %hr/
        .row.parts{:id => "comment-form-post-#{@post.id.to_s}"}
          = form_with model: [@post, Comment.new],  class: "w-100" do |f|
            = f.hidden_field :user_id, value: current_user.id
            = f.hidden_field :post_id, value: @post.id
            = f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off

app/views/users/show.html.haml
.profile-wrap
  .row
    .col-md-4.text-center
      = image_tag avatar_url(@user), class: "round-img"
    .col-md-8
      .row
        %h1= @user.name
        - if @user == current_user
          = link_to "プロフィールを編集", edit_user_registration_path, class: "btn btn-outline-dark edit-profile-btn"
          %button.setting{"data-target" => "#exampleModal", "data-toggle" => "modal", :type => "button"}
        #exampleModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
          .modal-dialog{:role => "document"}
            .modal-content
              .modal-header
                %h5#exampleModalLabel.modal-title 設定
                %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
                  %span{"aria-hidden" => "true"} ×
              .list-group.text-center
                = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "list-group-item list-group-item-action"
                = link_to "キャンセル", "#", class: "list-group-item list-group-item-action", "data-dismiss": "modal"
      .row
        %p
          = @user.email